//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class YSIDGAEntitiesConn : DbContext
    {
        public YSIDGAEntitiesConn()
            : base("name=YSIDGAEntitiesConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Shipper> Shippers { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<Territory> Territories { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<ProductsInventory> ProductsInventories { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ReceiveHeader> ReceiveHeaders { get; set; }
        public DbSet<MasterPeriod> MasterPeriods { get; set; }
        public DbSet<MasterUnit> MasterUnits { get; set; }
        public DbSet<TermOfPay> TermOfPays { get; set; }
        public DbSet<StockCard> StockCards { get; set; }
        public DbSet<MasterCurrency> MasterCurrencies { get; set; }
        public DbSet<POHeader> POHeaders { get; set; }
        public DbSet<MasterAssetsType> MasterAssetsTypes { get; set; }
        public DbSet<MasterRequestType> MasterRequestTypes { get; set; }
        public DbSet<MasterTransType> MasterTransTypes { get; set; }
        public DbSet<PODetail> PODetails { get; set; }
        public DbSet<ReceiveDetail> ReceiveDetails { get; set; }
        public DbSet<ReleaseDetail> ReleaseDetails { get; set; }
        public DbSet<ReleaseHeader> ReleaseHeaders { get; set; }
        public DbSet<RequestDetail> RequestDetails { get; set; }
        public DbSet<RequestHeader> RequestHeaders { get; set; }
        public DbSet<MasterOffice> MasterOffices { get; set; }
        public DbSet<Division> Divisions { get; set; }
        public DbSet<MasterTitle> MasterTitles { get; set; }
        public DbSet<CustomerDemographic> CustomerDemographics { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Departement> Departements { get; set; }
    
        public virtual int SP_CustOrderHist(string customerID)
        {
            var customerIDParameter = customerID != null ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CustOrderHist", customerIDParameter);
        }
    
        public virtual int SP_CustOrdersDetail(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CustOrdersDetail", orderIDParameter);
        }
    
        public virtual ObjectResult<SP_CustOrdersOrders_Result> SP_CustOrdersOrders(string customerID)
        {
            var customerIDParameter = customerID != null ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CustOrdersOrders_Result>("SP_CustOrdersOrders", customerIDParameter);
        }
    
        public virtual int SP_EmployeeSalesbyCountry(Nullable<System.DateTime> beginning_Date, Nullable<System.DateTime> ending_Date)
        {
            var beginning_DateParameter = beginning_Date.HasValue ?
                new ObjectParameter("Beginning_Date", beginning_Date) :
                new ObjectParameter("Beginning_Date", typeof(System.DateTime));
    
            var ending_DateParameter = ending_Date.HasValue ?
                new ObjectParameter("Ending_Date", ending_Date) :
                new ObjectParameter("Ending_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EmployeeSalesbyCountry", beginning_DateParameter, ending_DateParameter);
        }
    
        public virtual int SP_SalesByCategory(string categoryName, string ordYear)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var ordYearParameter = ordYear != null ?
                new ObjectParameter("OrdYear", ordYear) :
                new ObjectParameter("OrdYear", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SalesByCategory", categoryNameParameter, ordYearParameter);
        }
    
        public virtual int SP_SalesbyYear(Nullable<System.DateTime> beginning_Date, Nullable<System.DateTime> ending_Date)
        {
            var beginning_DateParameter = beginning_Date.HasValue ?
                new ObjectParameter("Beginning_Date", beginning_Date) :
                new ObjectParameter("Beginning_Date", typeof(System.DateTime));
    
            var ending_DateParameter = ending_Date.HasValue ?
                new ObjectParameter("Ending_Date", ending_Date) :
                new ObjectParameter("Ending_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SalesbyYear", beginning_DateParameter, ending_DateParameter);
        }
    
        public virtual ObjectResult<SP_TenMostExpensiveProducts_Result> SP_TenMostExpensiveProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TenMostExpensiveProducts_Result>("SP_TenMostExpensiveProducts");
        }
    
        public virtual ObjectResult<SPR_Categories_Result> SPR_Categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Categories_Result>("SPR_Categories");
        }
    
        public virtual ObjectResult<SPR_Suppliers_Result> SPR_Suppliers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Suppliers_Result>("SPR_Suppliers");
        }
    
        public virtual ObjectResult<SPR_Products_Result> SPR_Products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Products_Result>("SPR_Products");
        }
    
        public virtual ObjectResult<SPR_PODetail_Result> SPR_PODetail(Nullable<int> pOID)
        {
            var pOIDParameter = pOID.HasValue ?
                new ObjectParameter("POID", pOID) :
                new ObjectParameter("POID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_PODetail_Result>("SPR_PODetail", pOIDParameter);
        }
    
        public virtual ObjectResult<SPR_RequestDetail_Result> SPR_RequestDetail(Nullable<int> requestID)
        {
            var requestIDParameter = requestID.HasValue ?
                new ObjectParameter("RequestID", requestID) :
                new ObjectParameter("RequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_RequestDetail_Result>("SPR_RequestDetail", requestIDParameter);
        }
    
        public virtual int SPR_Departement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPR_Departement");
        }
    
        public virtual ObjectResult<SPR_Employee_Result> SPR_Employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Employee_Result>("SPR_Employee");
        }
    
        public virtual ObjectResult<SPR_POHeader_Result> SPR_POHeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_POHeader_Result>("SPR_POHeader");
        }
    
        public virtual ObjectResult<SPR_ProductsInventory_Result> SPR_ProductsInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_ProductsInventory_Result>("SPR_ProductsInventory");
        }
    
        public virtual ObjectResult<SPR_RequestHeader_Result> SPR_RequestHeader()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_RequestHeader_Result>("SPR_RequestHeader");
        }
    
        public virtual ObjectResult<SPR_Customers_Result> SPR_Customers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_Customers_Result>("SPR_Customers");
        }
    }
}
